import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className="min-h-screen bg-gradient-to-br from-indigo-400 via-sky-400 to-purple-500"
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-transparent`}
      >
        {children}
      </body>
    </html>
  );
}

